"""empty message

Revision ID: 0a8a4c3e4ddf
Revises: 2c687f87463b
Create Date: 2021-05-27 21:50:25.376197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a8a4c3e4ddf'
down_revision = '2c687f87463b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('match_mentor_id_fkey', 'match', type_='foreignkey')
    op.drop_constraint('match_learner_id_fkey', 'match', type_='foreignkey')
    op.create_foreign_key(None, 'match', 'user', ['learner_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'match', 'user', ['mentor_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('match_request_user_id_fkey', 'match_request', type_='foreignkey')
    op.create_foreign_key(None, 'match_request', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('user_company_user_id_fkey', 'user_company', type_='foreignkey')
    op.drop_constraint('user_company_company_id_fkey', 'user_company', type_='foreignkey')
    op.create_foreign_key(None, 'user_company', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'user_company', 'company', ['company_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('user_profile_user_id_fkey', 'user_profile', type_='foreignkey')
    op.create_foreign_key(None, 'user_profile', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('user_login_attempts_log_owner_id_fkey', 'user_login_attempts_log', schema='logs', type_='foreignkey')
    op.drop_column('user_login_attempts_log', 'owner_id', schema='logs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_login_attempts_log', sa.Column('owner_id', postgresql.UUID(), autoincrement=False, nullable=True), schema='logs')
    op.create_foreign_key('user_login_attempts_log_owner_id_fkey', 'user_login_attempts_log', 'user', ['owner_id'], ['id'], source_schema='logs')
    op.drop_constraint(None, 'user_profile', schema='public', type_='foreignkey')
    op.create_foreign_key('user_profile_user_id_fkey', 'user_profile', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_company', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'user_company', schema='public', type_='foreignkey')
    op.create_foreign_key('user_company_company_id_fkey', 'user_company', 'company', ['company_id'], ['id'])
    op.create_foreign_key('user_company_user_id_fkey', 'user_company', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'match_request', schema='public', type_='foreignkey')
    op.create_foreign_key('match_request_user_id_fkey', 'match_request', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'match', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'match', schema='public', type_='foreignkey')
    op.create_foreign_key('match_learner_id_fkey', 'match', 'user', ['learner_id'], ['id'])
    op.create_foreign_key('match_mentor_id_fkey', 'match', 'user', ['mentor_id'], ['id'])
    # ### end Alembic commands ###
